version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    versioning-strategy: increase
    labels:
      - "📦 Dependencies"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "📦 Dependencies"
      - "🚀 CI/CD"
    open-pull-requests-limit: 5
