export const GET_HOME_DATA = 'GET_HOME_DATA';

export const GET_ABOUTME_DATA = 'GET_ABOUTME_DATA';

export const GET_LAST_BLOG_DATA = 'GET_LAST_BLOG_DATA';
export const GET_ARTICLE_DATA = 'GET_ARTICLE_DATA';
