export const GET_HOME_DATA = 'GET_HOME_DATA';

export const GET_WHO_I_AM_DATA = 'GET_WHO_I_AM_DATA';

export const GET_LAST_BLOG_DATA = 'GET_LAST_BLOG_DATA';
export const GET_ARTICLE_DATA = 'GET_ARTICLE_DATA';
