export const GET_HOME_DATA = 'GET_HOME_DATA';
export const GET_ABOUTME_DATA = 'GET_ABOUTME_DATA';
export const GET_LAST_BLOG_DATA = 'GET_LAST_BLOG_DATA';
export const GET_ALL_BLOG_DATA = 'GET_ALL_BLOG_DATA';
export const GET_ARTICLE_DATA = 'GET_ARTICLE_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLEAN_NOTIFICATION = 'CLEAN_NOTIFICATION';
