import type { CategoryAllowed, TagsAllowed } from "../interfaces";

export const CategoryMap = new Map<CategoryAllowed, string>([
  ["engineering-leadership", "Liderazgo de Ingeniería"],
  ["platform-engineering", "Platform Engineering"],
  ["ai-native-engineering", "Ingeniería AI-Native"],
  ["career-strategy", "Estrategia de Carrera"],
  ["engineering-culture", "Cultura de Ingeniería"],
  ["developer-experience", "Developer Experience"],
  ["technical-decisions", "Decisiones Técnicas"],
  ["learning-in-tech", "Aprendizaje en Tecnología"],
]);

export const TagMap = new Map<TagsAllowed, string>([
  ["microfrontends", "Microfrontends"],
  ["design-systems", "Design Systems"],
  ["single-spa", "Single SPA"],
  ["frontend-architecture", "Arquitectura Frontend"],
  ["platform-thinking", "Platform Thinking"],
  ["technical-standards", "Estándares Técnicos"],
  ["governance", "Gobernanza"],
  ["scalability", "Escalabilidad"],
  ["modular-architecture", "Arquitectura Modular"],
  ["monorepo", "Monorepo"],
  ["frontend-platform", "Plataforma Frontend"],
  ["system-design", "Diseño de Sistemas"],
  ["event-driven-architecture", "Arquitectura Orientada a Eventos"],
  ["documentation", "Documentación"],
  ["open-spec", "Open Spec"],
  ["ai-assisted-development", "Desarrollo Asistido por IA"],
  ["llm", "LLM"],
  ["codex", "Codex"],
  ["openai", "OpenAI"],
  ["cloud-ai", "IA en la Nube"],
  ["opencode", "OpenCode"],
  ["automation", "Automatización"],
  ["prompt-engineering", "Prompt Engineering"],
  ["ai-workflows", "Flujos de Trabajo con IA"],
  ["developer-productivity", "Productividad del Desarrollador"],
  ["ai-integration", "Integración de IA"],
  ["ai-culture", "Cultura de IA"],
  ["engineering-management", "Gestión de Ingeniería"],
  ["technical-leadership", "Liderazgo Técnico"],
  ["team-growth", "Crecimiento del Equipo"],
  ["mentorship", "Mentoría"],
  ["trust-building", "Construcción de Confianza"],
  ["decision-making", "Toma de Decisiones"],
  ["stakeholder-management", "Gestión de Stakeholders"],
  ["feedback-culture", "Cultura de Feedback"],
  ["psychological-safety", "Seguridad Psicológica"],
  ["ownership", "Ownership"],
  ["accountability", "Responsabilidad"],
  ["organizational-maturity", "Madurez Organizacional"],
  ["career-growth", "Crecimiento Profesional"],
  ["tech-career", "Carrera en Tecnología"],
  ["promotion", "Promoción"],
  ["tl-to-em", "TL a EM"],
  ["career-transition", "Transición de Carrera"],
  ["professional-identity", "Identidad Profesional"],
  ["impostor-syndrome", "Síndrome del Impostor"],
  ["burnout", "Burnout"],
  ["tech-fatigue", "Fatiga Tecnológica"],
  ["continuous-learning", "Aprendizaje Continuo"],
  ["skill-development", "Desarrollo de Habilidades"],
  ["trade-offs", "Trade-offs"],
  ["business-alignment", "Alineación con el Negocio"],
  ["long-term-thinking", "Pensamiento a Largo Plazo"],
  ["risk-management", "Gestión de Riesgos"],
  ["prioritization", "Priorización"],
  ["strategy", "Estrategia"],
  ["focus", "Enfoque"],
  ["complexity", "Complejidad"],
  ["tech-debt", "Deuda Técnica"],
  ["maintainability", "Mantenibilidad"],
  ["onboarding", "Onboarding"],
  ["knowledge-sharing", "Compartir Conocimiento"],
]);
