import type { CategoryAllowed, TagsAllowed } from "../interfaces";

export const CategoryMap = new Map<CategoryAllowed, string>([
  ["engineering-leadership", "Engineering Leadership"],
  ["platform-engineering", "Platform Engineering"],
  ["ai-native-engineering", "AI Native Engineering"],
  ["career-strategy", "Career Strategy"],
  ["engineering-culture", "Engineering Culture"],
  ["developer-experience", "Developer Experience"],
  ["technical-decisions", "Technical Decisions"],
  ["learning-in-tech", "Learning in Tech"],
]);

export const TagMap = new Map<TagsAllowed, string>([
  ["microfrontends", "Microfrontends"],
  ["design-systems", "Design Systems"],
  ["single-spa", "Single SPA"],
  ["frontend-architecture", "Frontend Architecture"],
  ["platform-thinking", "Platform Thinking"],
  ["technical-standards", "Technical Standards"],
  ["governance", "Governance"],
  ["scalability", "Scalability"],
  ["modular-architecture", "Modular Architecture"],
  ["monorepo", "Monorepo"],
  ["frontend-platform", "Frontend Platform"],
  ["system-design", "System Design"],
  ["event-driven-architecture", "Event-Driven Architecture"],
  ["documentation", "Documentation"],
  ["open-spec", "Open Spec"],
  ["ai-assisted-development", "AI Assisted Development"],
  ["llm", "LLM"],
  ["codex", "Codex"],
  ["openai", "OpenAI"],
  ["cloud-ai", "Cloud AI"],
  ["opencode", "OpenCode"],
  ["automation", "Automation"],
  ["prompt-engineering", "Prompt Engineering"],
  ["ai-workflows", "AI Workflows"],
  ["developer-productivity", "Developer Productivity"],
  ["ai-integration", "AI Integration"],
  ["ai-culture", "AI Culture"],
  ["engineering-management", "Engineering Management"],
  ["technical-leadership", "Technical Leadership"],
  ["team-growth", "Team Growth"],
  ["mentorship", "Mentorship"],
  ["trust-building", "Trust Building"],
  ["decision-making", "Decision Making"],
  ["stakeholder-management", "Stakeholder Management"],
  ["feedback-culture", "Feedback Culture"],
  ["psychological-safety", "Psychological Safety"],
  ["ownership", "Ownership"],
  ["accountability", "Accountability"],
  ["organizational-maturity", "Organizational Maturity"],
  ["career-growth", "Career Growth"],
  ["tech-career", "Tech Career"],
  ["promotion", "Promotion"],
  ["tl-to-em", "TL to EM"],
  ["career-transition", "Career Transition"],
  ["professional-identity", "Professional Identity"],
  ["impostor-syndrome", "Impostor Syndrome"],
  ["burnout", "Burnout"],
  ["tech-fatigue", "Tech Fatigue"],
  ["continuous-learning", "Continuous Learning"],
  ["skill-development", "Skill Development"],
  ["trade-offs", "Trade-offs"],
  ["business-alignment", "Business Alignment"],
  ["long-term-thinking", "Long Term Thinking"],
  ["risk-management", "Risk Management"],
  ["prioritization", "Prioritization"],
  ["strategy", "Strategy"],
  ["focus", "Focus"],
  ["complexity", "Complexity"],
  ["tech-debt", "Tech Debt"],
  ["maintainability", "Maintainability"],
  ["onboarding", "Onboarding"],
  ["knowledge-sharing", "Knowledge Sharing"],
]);
